### PR TITLE
Do not allow switch to user with admin permissions

### PR DESCRIPTION
**Pull request by alexandermeindl**
I made some changes, that user can not switch to user with admin permissions. If there are more then one user with admin permissions, he/she would not like it, if someone else make changes with this credentials. It would be nice, if you can merge this change.

### CODE REVIEW

**Comment by batizhevsky** [comment]
Why not? I suppose if a user already with admin right it's assumed that we trust him

**Comment by alexandermeindl** [comment]
I see the problems more related to responsibility (who did the changes?).

**Comment by batizhevsky** [comment]
Yes, but in this case it's also a question: who did the action - user itself or admin?
It should be changes in the logger as well to show that an admin acted like the user, not user itself

**Comment by alexandermeindl** [comment]
Do switch to another user has a lot of problems regarding responsibility. Therefore from my point of view, an admin action (e.g. creating a issue) should always relayable.

**Comment by batizhevsky** [comment]
This extension intended to be a simple solution to view in redmine with eyes of other user. This broke all idea of it (you need this restriction, other users don't). As I said the problem could be solved with extended logging or, if possible, restricting any actions at all (but this is nearly impossible to implement, I suppose)

**Comment by alexandermeindl** [comment]
Ok, thanks for your response. I'll use my fork with this change.

**Pull request closed without merging**
